### ISSUE TITLE
Lab3 Handout : Fall 22 Update

### ISSUE THREAD

**Issue by Abhishek-P** [csci3155/pppl-lab3#2]
The Lab3 handout needs to be updated for Fall 22

An additional note:
Add clarity on how hidden tests run in the auto grader but are not present to run locally.
The students will need to add tests themselves in order to verify it locally. These tests are not part of the grading.

**Comment by vmaravind96** [comment]
Updated the content in lab3 pdf.

**Comment by Abhishek-P** [comment]
Merged and deployed
